### ISSUE TITLE
Install is deploying an empty Zip to lambda

### ISSUE THREAD

**Issue by dagisus** [tobilg/lsh#1]
One i run install inside lsh, the CF stack rollsback with an error while deploying the lambda function `Uploaded file must be a non-empty zip (Service: AWSLambdaInternal; Status Code: 400; Error Code: InvalidParameterValueException;`

**Comment by tobilg** [comment]
@dagisus Thanks for the feedback. Can you give me some details around your environment (OS etc.)? Thanks a lot!

**Comment by dagisus** [comment]
> @dagisus Thanks for the feedback. Can you give me some details around your environment (OS etc.)? Thanks a lot!

@tobilg  I'm running on MacOS 10.14.4 with Node 12.4.0,

**Comment by tobilg** [comment]
@dagisus Thanks! Can you please check if there's a `lambda.zip` file in your `/tmp` directory? If so, is it empty?

**Comment by tobilg** [comment]
Sorry, forgot to ask: You're using version `0.1.2`, right?

**Comment by tobilg** [comment]
@dagisus I just released version `0.1.3`, could you please update and check if your problems are fixed? Thanks a lot!

**Comment by Azulinho** [comment]
same here:
```
 >>> ls -ltr /tmp/lambda.zip                                                                                                                                   
-rw-r--r-- 1 azul azul 22 Jun 26 11:04 /tmp/lambda.zip                                                                                                         
1d [azul:~/tmp]↥ 8m7s $                                                                                                                                        
 >>> unzip -l /tmp/lambda.zip                                                                                                                                  
Archive:  /tmp/lambda.zip                                                                                                                                      
warning [/tmp/lambda.zip]:  zipfile is empty                                                                                                                   
1d [azul:~/tmp]↥ 8m15s 1 $                                                                                                                                     
 >>> lsh --version                                                                                                                                             
λ version                                                                                                                                                      
0.1.4           

```

**Comment by tobilg** [comment]
@Azulinho Are you using MacOS as well?

**Comment by Azulinho** [comment]
nope, linux

**Comment by tobilg** [comment]
@Azulinho / @dagisus I released a new version with an attempted fix for the problem. On my MacOS machine it works, as the previous versions as well. I suspect a combination of folder access rights and eventually other OS-based aspects as reasons.

Let me know it this helped.

**Comment by Azulinho** [comment]
works on my machine now

**Comment by tobilg** [comment]
Great, thanks for the feedback @Azulinho. Any updates @dagisus? Thanks in advance!
