### ISSUE TITLE
EFS Support

### ISSUE THREAD

**Issue by quinnypig** [tobilg/lsh#4]
This definitely needs some EFS support now that Lambda supports it. I have such awful, awful ideas for it...

**Comment by tobilg** [comment]
Thanks @QuinnyPig, that’s a great idea, I‘ll have a look on how to incorporate EFS. I was also thinking about layer support and „bring your own layer“. This could also enable some interesting use cases.

**Comment by tobilg** [comment]
@QuinnyPig I just released version `0.2.0` with EFS and VPC support. Let me know what you think, or if you find bugs. Thanks!

**Comment by tobilg** [comment]
Closing, please reopen if you encounter any problems
